apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy22
  labels:
    app: autodeploy22
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718860566715
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy22
  template:
    metadata:
      labels:
        app: autodeploy22
    spec:
      containers:
        - name: autodeploy22
          image: acrworkflow1718859866477.azurecr.io/image-workflow-1718860566715:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
