apiVersion: v1
kind: Service
metadata:
  name: autodeploy22
  namespace: namespace-workflow-1718860566715
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy22
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000